---
- name: Assert that the distribution and version are supported.
  assert:
    that:
      - ansible_distribution_version in wazuh_agent_supported_distros[ansible_distribution | lower] | map('string')
    fail_msg: "The distribution and/or version are not supported."
    quiet: true

- name: Include variables specific for the distribution.
  ansible.builtin.include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_distribution | lower }}.yml"

- name: Include install tasks.
  ansible.builtin.include_tasks:
    file: install.yml

- name: Include configure tasks.
  ansible.builtin.include_tasks:
    file: configure.yml
